apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: vks-cluster-11
  namespace: play-6t9bt
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    classRef:
      name: builtin-generic-v3.7.0
      namespace: vmware-system-vks-public
    version: v1.36.1---vmware.4-vkr.5
    variables:
      - name: vmClass
        value: best-effort-large
      - name: storageClass
        value: wkld01-cluster01-optimal-datastore-default-policy-autoraid
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-bab712043ac0065d3
    workers:
      machineDeployments:
        - class: node-pool
          name: vks-cluster-11-np-g64q
          replicas: 1
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-bab712043ac0065d3
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: vks-cluster-11-fluent-bit
spec:
  addonRef:
    name: fluent-bit
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: vks-cluster-11
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonConfig
metadata:
  annotations:
    clusteraddon.addons.kubernetes.vmware.com/owned-for-deletion: "true"
  name: vks-cluster-11-fluent-bit
spec:
  addonConfigDefinitionRef:
    name: fluent-bit.kubernetes.vmware.com.5.0.5---vmware.1-vks.1
    namespace: vmware-system-vks-public
  clusterName: vks-cluster-11
  values:
    fluent_bit:
      config:
        filters: |
          [FILTER]
            Name                kubernetes
            Match               kube.*
            Kube_URL            https://kubernetes.default.svc:443
            Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
            Kube_Tag_Prefix     kube.var.log.containers.
            Merge_Log           On
            Merge_Log_Key       log_processed
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On
          # 1. Ensure "text" and "originalText" exist at root
          [FILTER]
              Name                modify
              Match               *
              Copy                log text
              Copy                log originalText
              Set                 cluster vks-cluster-11
              Set                 log_type app
              Set                 piliev piliev
          [FILTER]
            Name                  modify
            Match                 kube.*
            Add                   text "K8s Container Logs"
            Copy                  kubernetes k8s
          [FILTER]
            Name                  nest
            Match                 kube.*
            Operation             lift
            Nested_Under          kubernetes
          [FILTER]
            Name                  modify
            Match                 kube.*
            Add                   text "K8s Container logs"
          [FILTER]
            Name                  modify
            Match                 kube_systemd.*
            Add                   text "Linux Daemon Logs"
          [FILTER]
            Name                  modify
            Match                 auth.*
            Add                   text "Linux Auth Logs"
          [FILTER]
            Name                  modify
            Match                 apiserver_audit.*
            Add                   text "Kubernetes API Server Audit Logs"
        outputs: |
          [OUTPUT]
            Name          http
            Match         *
            Host          vcflogs.mgmt.vks.lab
            Port          9543
            URI           api/v2/events
            Format        json
            tls.debug     4
            tls           on
            tls.verify    off